# Site Settings
title: Suyash Soni
url: 'http://suyash248.github.io'
baseurl: '/suyash248.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Suyash Soni
tagline: Backend Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '► ~3.5 years of experience while working in product-based startups. Currently working as ‘Software Developer’ on a SaaS product, involved in designing scalable system using microservice-based(SOA) architecture. 

► Open to explore new technologies/paradigm(Functional programming/Reactive programming/Big data/Machine learning etc.).
'

#sidebar links
email: suyash.soni248@gmail.com
phone: +91-9871897749
website: blog.webjeda.com #do not add http://
linkedin: https://www.linkedin.com/in/suyash248
github: https://www.github.com/suyash248
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
